---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: tripviewer
        image: registryjpn0775.azurecr.io/tripviewer:v1
        ports:
        - containerPort: 80
        env:
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile.api-dev"
        - name: TRIPS_API_ENDPOINT
          value: "http://trips.api-dev"
        - name: BING_MAPS_KEY
          value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: web-dev
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: tripviewer
